#il .dev serve per distinguere questo Dockerfile con quello di produzione, infatti dev sta per development 

FROM node:16-alpine

WORKDIR '/app'

COPY package.json .

RUN npm install

COPY . .

CMD ["npm", "run", "start"]

